"""The registry rendered for a person to read: one page, regenerated, never edited.

Committed to the repo so a reviewer sees an operation's class and version change in
the same diff as its declaration; `test_catalog_is_fresh` is what keeps the two equal.
"""

from __future__ import annotations

from pathlib import Path

from app.kernel.declare.registry import Operation, Registry

PAGE = Path(__file__).resolve().parents[2] / "OPERATIONS.md"

_HEADER = (
    "# Operations\n\n"
    "Generated by `agentquilt catalog` from the registry; edit the declarations,"
    " not this file.\n\n"
)
_COLUMNS = (
    "name",
    "mode",
    "reversal",
    "compensator",
    "aggregate",
    "stage",
    "taint",
    "version",
)


def render(registry: Registry) -> str:
    operations = registry.operations()
    if not operations:
        return f"{_HEADER}No operations declared.\n"
    rows = "\n".join(_row(registry, op) for op in operations)
    return (
        f"{_HEADER}| {' | '.join(_COLUMNS)} |\n"
        f"| {' | '.join('---' for _ in _COLUMNS)} |\n{rows}\n"
    )


def _row(registry: Registry, op: Operation) -> str:
    aggregate = f"{op.aggregate[0]}.{op.aggregate[1]}" if op.aggregate else None
    cells = (
        op.name,
        op.mode,
        op.reversal,
        op.compensator,
        aggregate,
        op.stage,
        op.taint,
        registry.version_id(op)[:12],
    )
    return "| " + " | ".join(cell or "-" for cell in cells) + " |"
